import { theme } from '../styles/theme.css';

export const metadata = {
  title: 'Welcome to apps/www',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={theme}>
      <body>{children}</body>
    </html>
  );
}
